config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :groups, except: :show do
    resources :posts, only: [:index, :show, :create] do
      resource :looks, only: [:create, :destroy]
      resources :comments, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/look.rb
class Look < ApplicationRecord
  belongs_to :post, counter_cache: :looked_count
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :comments
  has_many :looks, dependent: :destroy
  has_many :post_files, dependent: :destroy
  accepts_nested_attributes_for :post_files

  validates :content, presence: true
  validates :release_date, presence: true, if: :release_check?

  def self.release_post
    self.where(release_check: true).where('release_date >=?', Date.today).order(release_date: "ASC")
  end
end

app/models/post_file.rb
class PostFile < ApplicationRecord
  belongs_to :post

  mount_uploader :file, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :posts
  has_many :comments
  has_many :looks
  has_many :looked_posts, through: :looks, source: :post

  def name
    "#{self.lastname} #{self.firstname}"
  end

  def already_looked?(post)
    self.looks.exists?(post_id: post.id)
  end

  def self.search(input, id)
    return nil if input == ""
    User.where(['lastname LIKE? OR firstname LIKE?', "%#{input}%", "%#{input}%"] ).where.not(id: id).limit(10)
  end

  validates :firstname, presence: true
  validates :lastname, presence: true

  mount_uploader :avater, ImageUploader
  mount_uploader :timetable, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      @comments = @post.comments.includes(:user).order("created_at DESC")
      redirect_to group_post_path(id: @post.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def correct_user
    if request.referer.nil?
      redirect_to root_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :correct_user

  def index
    @groups = current_user.groups.order(name: "ASC")
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_posts_path(@group)
    else
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def correct_user
    if request.referer.nil?
      redirect_to root_path
    end
  end
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  before_action :set_group

  def create
    @post = Post.find(params[:post_id])
    @look = current_user.looks.create(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @look = Look.find_by(post_id: params[:post_id], user_id: current_user.id)
    @look.destroy
  end

  private
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user
  before_action :set_group

  def index
    @post = Post.new
    @post_file = @post.post_files.build
    @posts = @group.posts.includes(:user).order(created_at: "DESC")
    @looks = Look.new
  end

  def show
    @post = Post.find(params[:id])
    @looks = Look.new
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: "DESC")
  end

  def create
    @post = @group.posts.new(post_params)
    if @post.save
      if params[:post_files].present?
        params[:post_files][:file].each do |a|
          @post_file = @post.post_files.create!(file: a, post_id: @post.id)
        end
      end
      respond_to do |format|
        format.json
      end
    else
      @posts = @group.posts.includes(:user).order(created_at: "DESC")
      render :index
    end
  end

  private
  def post_params
    params.require(:post).permit(:content, :release_check, :release_date, post_files_attributes: [:file]).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def correct_user
    if request.referer.nil?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, except: :index

  def index
    @post_releases = Post.release_post
    @posts = @post_releases.where(group_id: current_user.groups.ids).limit(6)
    @users = User.search(params[:keyword], current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :avater, :email, :introduce, :timetable)
  end

  def correct_user
    if request.referer.nil?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    #error_explanation
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .field
    .field__label
      = f.label "グループ名"
    .field__input
      = f.text_field :name, placeholder: "グループ名を入力してください"
  .field
    .field__label
      = f.label "メンバーを追加"
    .field__input
      %input{ type: "text", placeholder: "追加したいユーザー名を入力してください", id: "user-search-field" }/
      #user-search-result
  .field
    .field__label
      = f.label "メンバー"
    .field__users
      .group-user
        %input{ name: "group[user_ids][]", type: "hidden", value: current_user.id }
          %p.group-user__name= current_user.name
      .js-add-user

      - group.users.each do |user|
        - if current_user != user
          .group-user
            %input{ name: "group[user_ids][]", type: "hidden", value: user.id, class: "already-added-user" }
              %p.group-user__name
                = user.name
              %a.user-search-remove.group-user__btn.group-user__btn--remove
                削除

  = f.submit class: 'btn'

app/views/groups/edit.html.haml
= render "layouts/header"
.body
  .group-form
    %h1 グループ編集
    = render partial: 'form', locals: { group: @group }
    .field
      = link_to group_path(@group), method: :delete, class: 'field__destroy' do
        グループを削除する

app/views/groups/index.html.haml
= render "layouts/header"
.chat-page
  =render "posts/left_bar"

app/views/groups/new.html.haml
= render "layouts/header"
.body
  .group-form
    %h1 新規グループ作成
    = render partial: 'form', locals: { group: @group }

app/views/layouts/_header.html.haml
.header
  .header__left
    = link_to root_path do
      = image_tag "logo.png", class: "header__left__logo"
  .header__middle
    = l Date.today, format: :short
  .header__right
    .current_user
      = link_to user_path(current_user), class: 'current_user__info' do
        .current_user__info--avater
          = image_tag current_user.avater.url, id: 'avater'
        .current_user__info--name
          = current_user.name
    .user-links
      = link_to edit_user_path(current_user), class: 'user-links__icon' do
        = icon('fa', 'user-cog')
        %h5 編集
      = link_to destroy_user_session_path, method: :delete, class: 'user-links__icon' do
        = icon('fa', 'sign-out-alt')
        %h5 ログアウト

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ラクスク
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/looks/_look.html.haml
.look{id: "look_#{post.id}"}
  .looked-count
    = icon('fa', 'check')
    = "#{post.looks.count} 人"
  - if current_user.already_looked?(post)
    = link_to '見ましたを解除', group_post_looks_path(@group, post), method: :delete, remote: true, class: 'look-btn'
  - else
    = link_to '見ました', group_post_looks_path(@group, post), method: :post, remote: true, class: 'look-btn'

app/views/looks/create.js.haml
$("#{"#look_#{@post.id}"}").html("#{j(render partial: 'looks/look', locals: { post: @post })}");

app/views/looks/destroy.js.haml
$("#{"#look_#{@post.id}"}").html("#{j(render partial: 'looks/look', locals: { post: @post })}");

app/views/posts/_left_bar.html.haml
.left_bar
  =link_to new_group_path, class: 'group-new' do
    新規グループ作成
  .joined-groups
    - current_user.groups.each do |group|
      = link_to group_posts_path(group), class: 'group' do
        = group.name

app/views/posts/_post.html.haml
.post
  .top
    = image_tag post.user.avater.url, id: 'avater'
    .top__right
      .top__userinfo
        .top__userinfo--user-name
          = post.user.name
        .top__userinfo--datetime
          = l post.created_at, format: :datetime
      - if post.release_check?
        .top__release
          .top__release--date
            予定に登録されています
            %br
            = l post.release_date
  .middle
    .post-content
      = simple_format(post.content)
    - if post.post_files.present?
      .post-files
        - post.post_files.each do |file|
          %object{data: file.file.url, class: 'post-files__file'}
    = render partial: 'looks/look', locals: { post: post }
  .bottom
    = link_to group_post_path(@group, post), class: 'comment-link' do
      = icon('fa', 'comment-dots')
      コメントする
      - if post.comments.present?
        = ",  #{post.comments.length}件"

app/views/posts/_right_body.html.haml
.right_body
  .current_group
    .current_group__left
      = @group.name
      .current_group__left__member
        = "メンバー：#{@group.users.length}人"
    =link_to edit_group_path(@group), class: 'current_group__right' do
      編集
  .scroll-show
    .post-form
      = image_tag current_user.avater.url, id: 'avater'
      .input-box
        = form_for [@group, @post] do |f|
          = f.text_area :content, id: 'textarea', class: 'input-box__content', placeholder: '投稿文を入力してください（予定に登録した場合、45文字までが登録された予定欄に表示されます）'
          .input-box__bottom
            .input-box__bottom__release
              = f.check_box :release_check, class: 'input-box__bottom__release__check', id: 'release_check'
              予定に登録
              = f.date_field :release_date, class: 'input-box__bottom__release__date', id: 'release_date'
            .input-box__bottom__files
              = f.fields_for :post_files do |i|
                = i.file_field :file, multiple: true, name: "post_files[file][]"
            = f.submit '投稿', class: 'submit-btn'
    .posts
      = render @posts

app/views/posts/index.html.haml
= render "layouts/header"
.chat-page
  = render "posts/left_bar"
  = render "posts/right_body"

app/views/posts/show.html.haml
= render "layouts/header"
.chat-page
  = render "posts/left_bar"
  .right_body
    .current_group
      = @group.name
    .scroll-show
      .post
        .top
          = image_tag @post.user.avater.url, id: 'avater'
          .top__right
            .top__userinfo
              .top__userinfo--user-name
                = @post.user.name
              .top__userinfo--datetime
                = l @post.created_at, format: :datetime
            - if @post.release_check?
              .top__release
                .top__release--date
                  予定に登録されています
                  %br
                  = l @post.release_date
        .middle
          .post-content
            = simple_format(@post.content)
          - if @post.post_files.present?
            .post-files
              - @post.post_files.each do |file|
                %object{data: file.file.url, class: 'post-files__file'}
          = render partial: 'looks/look', locals: { post: @post }
      .post-form
        = image_tag current_user.avater.url, id: 'avater'
        .input-box
          = form_for [@group, @post, @comment] do |f|
            = f.text_area :content, id: 'textarea', class: 'input-box__content', placeholder: 'コメントを入力してください'
            .input-box__bottom
              = f.submit '投稿', class: 'submit-btn'
      .comments__count
        = icon('fa', 'comment-dots')
        コメント一覧
        - if @post.comments.present?
          = ",  #{@post.comments.length}件"
      .comments
        - @comments.each do |comment|
          .comment
            .top
              = image_tag comment.user.avater.url, id: 'avater'
              .top__right
                .top__userinfo
                  .top__userinfo--user-name
                    = comment.user.name
                  .top__userinfo--datetime
                    = l comment.created_at, format: :datetime
            .middle
              .post-content
                = simple_format(comment.content)

app/views/users/edit.html.haml
= render "layouts/header"
.body
  .user-form
    = form_for(current_user) do |f|
      .field
        .field__label
          = f.label "プロフィール写真"
        .field__input
          = f.file_field :avater
      .field
        .field__label
          = f.label "氏名"
        .field__input
          = f.text_field :lastname
          = f.text_field :firstname
      .field
        .field__label
          = f.label "メールアドレス"
        .field__input
          = f.email_field :email
      .field
        .field__label
          = f.label "自己紹介文"
        .field__input
          = f.text_area :introduce, class: 'field__input__textarea'
      .field
        .field__label
          = f.label "時間割登録"
        .field__input
          = f.file_field :timetable, autofocus: true
      = f.submit "更新する", class: 'btn'

app/views/users/index.html.haml
= render "layouts/header"
.body
  .today-info
    = icon('fa', 'thumbtack')
    登録された予定
    .information
      - @posts.each do |post|
        .release_post
          .release_post__date
            = l post.release_date
            ▶︎
          .release_post__content
            = link_to group_post_path(post.group.id, post) do
              = post.content.truncate(45)
  .menu-list
    .menu
      .menu__block
        = link_to groups_path, class: 'menu__block__icon' do
          = icon('fa', 'users')
      .menu__text
        グループチャット

app/views/users/show.html.haml
= render "layouts/header"
.body
  .timetable
    - if current_user.timetable?
      = image_tag current_user.timetable.url, class: 'timetable__image'
    - else
      = image_tag "default_timetable_image.png", class: 'timetable__image'
  .profile
    紹介文
    .profile__introduce
      = simple_format(current_user.introduce)